import Head from "next/head";
import Social from '../components/Social';
import MainSection from '../components/MainSection';
import AboutSection from '../components/AboutSection';
import StackSection from "../components/StackSection";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Soheyl Delshad | Web Developer</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Social/>
            <MainSection/>
            <AboutSection/>
            <StackSection/>
        </div>
    );
}
